### PR TITLE
OT169-70: Delete Member Endpoint

### PR DESCRIPTION
**Pull request by FrancoFelg**
This PR adds:

> Changes from OT169-70
> Delete Member Endpoint
> Fixes bugs from the entity Member (@SQLDelete)

### CODE REVIEW

**Comment by CamilaGuz** [comment]
Código claro y sin conflictos!

**Comment by srotaka** [comment]
Todo OK, Fran!

**Comment by josue1dario2** [comment]
Muy bien y sin conflictos !!

**Review by srotaka — APPROVED** [review]
Aprobadísimo, Fran!!

**Pull request merged**
